# Generated by Django 5.0.6 on 2024-06-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Identity', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=10)),
                ('IDCard', models.CharField(max_length=20)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
