# Generated by Django 5.0.6 on 2024-06-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocean_current', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OceanCurrentData',
            fields=[
                ('CurrentID', models.AutoField(primary_key=True, serialize=False)),
                ('station', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('visibility', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('air_pressure', models.FloatField()),
                ('sea_temperature', models.FloatField()),
                ('wind_wave_height', models.FloatField()),
                ('wind_wave_period', models.FloatField()),
            ],
        ),
    ]
