# Generated by Django 5.0.6 on 2024-06-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocean_current', '0002_oceancurrentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='oceancurrentdata',
            name='air_temperature',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
